# see package.yml for usage 
name: 'AMROS Tests'
description: 'Runs launch files installing a specific version of a binary.'
inputs:
  package-file-path:  
    description: 'The host past generated artifact to be installed.'
    required: false
  launch-file-path:  
    description: 'Aboslute or relative path, in the AMROS container, to the launch file to be tested.'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args: # see entrypoint.sh for the recipient of these - order matters
    - ${{ inputs.launch-file-path }}
    - ${{ inputs.package-file }}
    
