name: Story Development
on:
  push:
    branches-ignore:
      - master
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Test super in AMROS
        uses: ./
        with:
          launch-file-path: /home/ubuntu/launch/super/play.launch     
          release-repo-entitlement: ${{ secrets.CLOUDSMITH_READ_RELEASE_ENTITLEMENT }}   


